[package]
name = "amulet"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
env_logger = "0.11.5"
log = "0.4.22"
serde = "1.0.219"
serde_json = "1.0.140"
